---
title: "MED131 - Biostatistics - Fall 2022"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r schedule, echo=FALSE}
suppressMessages(sched_df <- readxl::read_excel("misc/MED131_lectures.xlsx"))

sched_df$Slides <- sched_df$`R script` <-NULL
sched_df$R_lecture <-  ""
colnames(sched_df)[5] <- "review"
sched_df$review[is.na(sched_df$review)] <- ""
sched_df$HW[is.na(sched_df$HW)] <- ""

base_url <- "https://github.com/egeulgen/MED131_22_23/blob/main/"

# links to HWs
sched_df$HW[4] <- kableExtra::cell_spec(sched_df$HW[4], "html", link = paste0(base_url, "Homeworks/HW-1.R"))
sched_df$HW[8] <- kableExtra::cell_spec(sched_df$HW[8], "html", link = paste0(base_url, "Homeworks/HW2.pdf"))
sched_df$HW[12] <- kableExtra::cell_spec(sched_df$HW[12], "html", link = paste0(base_url, "Homeworks/HW3.pdf"))

# links to R lectures
sched_df$R_lecture[5] <- kableExtra::cell_spec("Conf.Int.", "html", link = paste0(base_url, "scripts/4.basics_conf_int.pdf"))
sched_df$R_lecture[6] <- kableExtra::cell_spec("t tests", "html", link = paste0(base_url, "scripts/5.t_test_examples.pdf"))
sched_df$R_lecture[7] <- kableExtra::cell_spec("ANOVA", "html", link = paste0(base_url, "scripts/6.ANOVA_examples.pdf"))
sched_df$R_lecture[11] <- kableExtra::cell_spec("non-param", "html", link = paste0(base_url, "scripts/10.nonparam.pdf"))
sched_df$R_lecture[12] <- kableExtra::cell_spec("regression", "html", link = paste0(base_url, "scripts/11.regression.pdf"))

# links to lectures
sched_df$Subject[1] <- kableExtra::cell_spec(sched_df$Subject[1], "html", link = paste0(base_url, "lectures/0.intro.pdf"))
sched_df$Subject[2] <- kableExtra::cell_spec(sched_df$Subject[2], "html", link = paste0(base_url, "lectures/1.overview_one_var_EDA.pdf"))
sched_df$Subject[3] <- kableExtra::cell_spec(sched_df$Subject[3], "html", link = paste0(base_url, "lectures/2.Inro_prog.pdf"))
sched_df$Subject[4] <- kableExtra::cell_spec(sched_df$Subject[4], "html", link = paste0(base_url, "lectures/3.two_var_EDA_RV.pdf"))
sched_df$Subject[5] <- kableExtra::cell_spec(sched_df$Subject[5], "html", link = paste0(base_url, "lectures/4.hypothesis_testing_one_sample.pdf"))
sched_df$Subject[6] <- kableExtra::cell_spec(sched_df$Subject[6], "html", link = paste0(base_url, "lectures/5.two_sample.pdf"))
sched_df$Subject[7] <- kableExtra::cell_spec(sched_df$Subject[7], "html", link = paste0(base_url, "lectures/6.ANOVA.pdf"))
sched_df$Subject[8] <- kableExtra::cell_spec(sched_df$Subject[8], "html", link = paste0(base_url, "lectures/7.chi_squared.pdf"))
sched_df$Subject[10] <- kableExtra::cell_spec(sched_df$Subject[10], "html", link = paste0(base_url, "lectures/9.nonparametric_tests.pdf"))
sched_df$Subject[11] <- kableExtra::cell_spec(sched_df$Subject[11], "html", link = paste0(base_url, "lectures/10.linear_regression.pdf"))
sched_df$Subject[12] <- kableExtra::cell_spec(sched_df$Subject[12], "html", link = paste0(base_url, "lectures/11.logistic_poisson_regression.pdf"))
sched_df$Subject[13] <- kableExtra::cell_spec(sched_df$Subject[13], "html", link = paste0(base_url, "lectures/12.sampling_missing.pdf"))


sched_df$review[8] <- kableExtra::cell_spec(sched_df$review[8], "html", link = paste0(base_url, "lectures/7.MT_review.pdf"))
sched_df$review[15] <- "review before final"

kableExtra::row_spec(kableExtra::row_spec(knitr::kable(sched_df, format = "html", escape = FALSE), 
                                          which(grepl("Midterm", sched_df$Subject)), 
                                          bold = TRUE, background = "#F4B41A"), 
                     nrow(sched_df), 
                     bold = TRUE, background = "#E2725A")
```
